//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguaDeMaria.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.DeliveryReceipts = new HashSet<DeliveryReceipt>();
            this.ReturnReceipts = new HashSet<ReturnReceipt>();
            this.SalesInvoices = new HashSet<SalesInvoice>();
        }
    
        public int CustomerId { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public int CustomerTypeId { get; set; }
        public string Address { get; set; }
        public string GPSCoordinate { get; set; }
    
        public virtual CustomerType CustomerType { get; set; }
        public virtual ICollection<DeliveryReceipt> DeliveryReceipts { get; set; }
        public virtual ICollection<ReturnReceipt> ReturnReceipts { get; set; }
        public virtual ICollection<SalesInvoice> SalesInvoices { get; set; }
    }
}
