//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguaDeMaria.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryReceipt
    {
        public DeliveryReceipt()
        {
            this.DeliveryReceiptDetails = new HashSet<DeliveryReceiptDetail>();
        }
    
        public int DeliveryReceiptId { get; set; }
        public string DRNumber { get; set; }
        public System.DateTime DRDate { get; set; }
        public int CustomerId { get; set; }
        public int SalesInvoiceId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual SalesInvoice SalesInvoice { get; set; }
        public virtual ICollection<DeliveryReceiptDetail> DeliveryReceiptDetails { get; set; }
    }
}
