//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguaDeMaria.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryReceiptDetail
    {
        public int DeliveryReceiptDetailId { get; set; }
        public int DeliveryReceiptId { get; set; }
        public int ProductTypeId { get; set; }
        public int Quantity { get; set; }
    
        public virtual DeliveryReceipt DeliveryReceipt { get; set; }
        public virtual ProductType ProductType { get; set; }
    }
}
