//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguaDeMaria.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductType
    {
        public ProductType()
        {
            this.DeliveryReceiptDetails = new HashSet<DeliveryReceiptDetail>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.ReturnReceiptDetails = new HashSet<ReturnReceiptDetail>();
            this.SalesInvoiceDetails = new HashSet<SalesInvoiceDetail>();
        }
    
        public int ProductTypeId { get; set; }
        public string ProductType1 { get; set; }
        public string Description { get; set; }
        public decimal BasePrice { get; set; }
        public int IsInvetoriable { get; set; }
    
        public virtual ICollection<DeliveryReceiptDetail> DeliveryReceiptDetails { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<ReturnReceiptDetail> ReturnReceiptDetails { get; set; }
        public virtual ICollection<SalesInvoiceDetail> SalesInvoiceDetails { get; set; }
    }
}
