//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguaDeMaria.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesInvoice
    {
        public SalesInvoice()
        {
            this.DeliveryReceipts = new HashSet<DeliveryReceipt>();
            this.SalesInvoiceDetails = new HashSet<SalesInvoiceDetail>();
        }
    
        public int SalesInvoiceId { get; set; }
        public string InvoiceNumber { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public int CustomerId { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> OrderId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<DeliveryReceipt> DeliveryReceipts { get; set; }
        public virtual Order Order { get; set; }
        public virtual ICollection<SalesInvoiceDetail> SalesInvoiceDetails { get; set; }
    }
}
